//@ui5-bundle gitpg/mybtpapp/Component-preload.js
sap.ui.require.preload({
	"gitpg/mybtpapp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","gitpg/mybtpapp/model/models"],function(e,t,i){"use strict";return e.extend("gitpg.mybtpapp.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"gitpg/mybtpapp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(t){"use strict";return t.extend("gitpg.mybtpapp.controller.controller.App",{onInit(){}})});
},
	"gitpg/mybtpapp/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","gitpg/mybtpapp/model/formatter"],function(e,t,o,n){"use strict";return e.extend("gitpg.mybtpapp.controller.BaseController",{formatter:n,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){const e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"gitpg/mybtpapp/controller/MainView.controller.js":function(){sap.ui.define(["./BaseController"],function(n){"use strict";return n.extend("gitpg.mybtpapp.controller.MainView",{onInit:function(){}})});
},
	"gitpg/mybtpapp/i18n/i18n.properties":'# This is the resource bundle for gitpg.mybtpapp\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Title of gitpg.mybtpapp\n\n#YDES: Application description\nappDescription=Description of gitpg.mybtpapp\r\n#XTIT: Main view title\ntitle=Title of gitpg.mybtpapp',
	"gitpg/mybtpapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"gitpg.mybtpapp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap-ux/fiori-freestyle-writer:basic","version":"0.11.15"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"gitpg.mybtpapp.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"gitpg.mybtpapp.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMainView","pattern":":?query:","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"MainView","viewName":"MainView"}}},"rootView":{"viewName":"gitpg.mybtpapp.view.App","type":"XML","async":true,"id":"App"}}}',
	"gitpg/mybtpapp/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"gitpg/mybtpapp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){const i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"gitpg/mybtpapp/view/App.view.xml":'<mvc:View controllerName="gitpg.mybtpapp.controller.App" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"gitpg/mybtpapp/view/MainView.view.xml":'<mvc:View controllerName="gitpg.mybtpapp.controller.MainView" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Page id="page" title="{i18n>title}"><content /></Page></mvc:View>\n'
});
